"""Default structured content for each public page section (images excluded)."""

SECTION_CONTENT = {
    'hero': {
        'badge': 'Uganda · East Africa · Global Markets',
        'headline': 'Building Wealth Through',
        'highlight': 'Disciplined',
        'headline_suffix': 'Digital Asset Investing',
        'subheadline': 'Helping entrepreneurs, institutions, and sophisticated investors navigate Bitcoin, digital assets, and global markets through professional portfolio management, strategic risk controls, and data-driven investment decisions.',
        'cta_primary': 'Schedule a Consultation',
        'cta_secondary': 'View Investment Philosophy',
        'portrait_alt': 'Twaresh Denis, Portfolio Manager and Digital Asset Investment Strategist',
        'badge_float': 'Risk Framework · Active',
        'card_title': 'Portfolio Intelligence',
        'card_live': 'Illustrative',
        'risk_posture': 'Defensive',
        'cycle_phase': 'Accumulation',
    },
    'ticker': {
        'label': 'Live Markets',
        'note': 'Market data: CoinGecko · ~60s refresh · Informational only',
    },
    'strip': {
        'items': [
            'Capital Preservation', 'Risk-Adjusted Returns', 'Bitcoin & Digital Assets',
            'Macro Research', 'Institutional Discipline', 'Market Cycle Analysis', 'Quantitative Frameworks',
        ],
    },
    'about': {
        'eyebrow': 'About',
        'title_html': 'Meet <em>Twaresh Denis</em>',
        'paragraphs': [
            'Twaresh Denis is a <strong>Portfolio Manager and Digital Asset Investment Strategist</strong> focused on helping investors preserve capital, manage risk, and pursue long-term growth opportunities within global financial markets.',
            'Serving clients throughout <strong>Uganda, East Africa, and the broader African market</strong>, he works with investors seeking professional guidance in an increasingly complex investment environment — combining global market intelligence with a deep understanding of the African investment landscape.',
        ],
        'approach_list': [
            'Macro-economic research', 'Market cycle analysis', 'Quantitative trading frameworks',
            'Institutional-grade risk management', 'Advanced portfolio analytics', 'Digital asset market intelligence',
        ],
        'cred_rows': [
            {'k': 'Experience', 'v': '8+ years across digital asset spot & futures markets'},
            {'k': 'Leadership', 'v': 'Director — Arivana Investments Ltd'},
            {'k': 'Operations', 'v': 'Chief Operating Officer — Erudites Global Ltd'},
            {'k': 'Coverage', 'v': 'Bitcoin · Ethereum · Solana · BNB · Zcash'},
        ],
        'badges': ['Uganda Blockchain Association', 'Digital Assets Traders Association'],
        'signature': 'Twaresh Denis',
        'portrait_name': 'Twaresh Denis',
        'portrait_title': 'Digital Asset Investment Strategist',
    },
    'record': {
        'eyebrow': 'Track Record',
        'title_html': 'Experience, <em>Measured</em>',
        'footnote': '† Historical figures reflect Twaresh Denis\'s past trading and portfolio activity over the stated period and are presented for informational purposes only. <strong>Past performance does not guarantee future results.</strong> Digital asset markets are highly volatile; returns vary significantly across market cycles and individual outcomes will differ. No future rate of return is promised or implied.',
    },
    'philosophy': {
        'eyebrow': 'Investment Philosophy',
        'title_html': 'Capital Preservation <em>First</em>',
        'quote_html': '"Successful investing begins with <span>protecting capital</span>. The objective is not simply to pursue returns — it is to build resilient portfolios capable of navigating changing market conditions."',
        'pillars': [
            {'idx': 'I.', 'title': 'Risk-Adjusted Returns', 'text': 'Performance is measured against the risk taken to achieve it. Every position is evaluated through the lens of expected return relative to potential drawdown.'},
            {'idx': 'II.', 'title': 'Strategic Asset Allocation', 'text': 'Deliberate capital distribution across digital assets, hedges, and liquidity reserves — structured around each client\'s objectives and time horizon.'},
            {'idx': 'III.', 'title': 'Portfolio Diversification', 'text': 'Concentration risk is managed through disciplined exposure limits across assets, sectors, and market structures.'},
            {'idx': 'IV.', 'title': 'Dynamic Risk Controls', 'text': 'Position sizing, drawdown thresholds, and systematic monitoring designed to respond to volatility rather than react to it.'},
            {'idx': 'V.', 'title': 'Market Cycle Awareness', 'text': 'Allocation posture adapts to where markets sit within accumulation, expansion, distribution, and contraction phases.'},
            {'idx': 'VI.', 'title': 'Institutional-Grade Research', 'text': 'Decisions are grounded in macro data, on-chain analytics, market structure, and quantitative signals — never sentiment or speculation.'},
        ],
        'closing_html': '"We do not chase markets. We build <strong>frameworks that endure them</strong>."',
    },
    'services': {
        'eyebrow': 'Services',
        'title_html': 'Institutional Capability,<br><em>Personal Alignment</em>',
        'lead': 'A focused suite of advisory and management services for investors seeking disciplined exposure to digital assets and global markets.',
        'items': [
            {'title': 'Portfolio Management', 'text': 'Professional management of digital asset portfolios designed around client objectives and risk tolerance.', 'bullets': ['Objective-driven mandates', 'Defined risk parameters', 'Ongoing rebalancing & reporting']},
            {'title': 'Institutional Advisory', 'text': 'Strategic guidance for institutions, corporate treasuries, family offices, and investment firms exploring digital asset exposure.', 'bullets': ['Treasury allocation frameworks', 'Governance & custody guidance', 'Board-level education']},
            {'title': 'Private Wealth Consulting', 'text': 'Personalized investment planning for entrepreneurs, executives, and high-net-worth individuals.', 'bullets': ['Wealth structuring strategy', 'Long-term allocation planning', 'Discreet, confidential counsel']},
            {'title': 'Market Intelligence', 'text': 'Research-driven insights covering Bitcoin, Ethereum, digital assets, AI-related investment themes, global macro trends, and alternative investments.', 'bullets': ['Cycle & on-chain analysis', 'Macro & liquidity briefings', 'Thematic opportunity research']},
            {'title': 'Risk Management Frameworks', 'text': 'Implementation of sophisticated portfolio monitoring and capital preservation methodologies.', 'bullets': ['Drawdown & exposure limits', 'Volatility-aware sizing', 'Continuous portfolio monitoring']},
            {'title': 'Investor Education & Onboarding', 'text': 'A structured onboarding process that ensures every client understands the strategy, the risks, and the framework before capital is allocated.', 'bullets': ['Discovery & suitability review', 'Strategy walkthrough', 'Transparent documentation']},
        ],
    },
    'why': {
        'eyebrow': 'Why Investors Work With Us',
        'title_html': 'A Standard of <em>Discipline</em>',
        'items': [
            {'num': '01', 'title': 'Institutional Discipline', 'text': 'Investment decisions driven by research, data, and structured processes — never emotion or market noise.'},
            {'num': '02', 'title': 'Advanced Technology', 'text': 'Professional-grade analytics, market intelligence platforms, and portfolio monitoring systems applied to every mandate.'},
            {'num': '03', 'title': 'Risk-Focused Approach', 'text': 'Comprehensive frameworks designed to manage downside risk and preserve long-term capital through full market cycles.'},
            {'num': '04', 'title': 'Global Perspective', 'text': 'Analysis of international markets with a focus on opportunities relevant to African investors and institutions.'},
            {'num': '05', 'title': 'Client-Centric Strategy', 'text': 'Every portfolio is aligned with the unique objectives, time horizon, and risk profile of each investor.'},
            {'num': '06', 'title': 'Transparent Process', 'text': 'Clear communication, documented frameworks, and honest conversations about both opportunity and risk.'},
        ],
    },
    'risk': {
        'eyebrow': 'Risk Management Framework',
        'title_html': 'How Capital Is <em>Protected</em>',
        'lead': 'Every mandate operates inside a documented risk architecture. These are the standing controls applied before any position is taken.',
        'table_rows': [
            {'pillar': 'Position Sizing', 'approach': 'Exposure per instrument capped relative to portfolio value and prevailing volatility, with hard per-trade limits.', 'objective': 'No single position can impair the portfolio.'},
            {'pillar': 'Drawdown Controls', 'approach': 'Pre-defined portfolio drawdown thresholds trigger systematic de-risking and review — not discretionary hope.', 'objective': 'Preserve capital through adverse conditions.'},
            {'pillar': 'Liquidity Management', 'approach': 'Strategic cash and stable reserves maintained at all times; positions sized to exit without market impact.', 'objective': 'Stay solvent, stay opportunistic.'},
            {'pillar': 'Cycle-Adaptive Exposure', 'approach': 'Net exposure adjusts with accumulation, expansion, distribution, and contraction phases of the market cycle.', 'objective': 'Respond to volatility rather than react.'},
            {'pillar': 'Hedging Discipline', 'approach': 'Futures used to hedge spot exposure and manage downside — never as uncontrolled leverage.', 'objective': 'Asymmetric protection of long-term holdings.'},
        ],
        'chips': [
            {'title': 'Spot & Derivatives Execution', 'text': 'Tier-one venues across spot and futures markets'},
            {'title': 'Custody Practices', 'text': 'Segregated, security-first asset custody discipline'},
            {'title': 'Real-Time Monitoring', 'text': 'Continuous portfolio and exposure surveillance'},
            {'title': 'Quantitative Signal Stack', 'text': 'Data-driven entries, exits, and risk triggers'},
        ],
    },
    'markets': {
        'eyebrow': 'Markets Covered',
        'title_html': 'Where We Focus<br><em>Our Research</em>',
        'lead': 'Coverage across the digital asset economy and the global markets that shape it — analyzed through an institutional lens.',
        'tags': ['Bitcoin', 'Ethereum', 'Major Cryptocurrencies', 'Digital Asset Infrastructure', 'AI & Technology Opportunities', 'Global Equities', 'Alternative Investments'],
        'geo_title': 'Serving Investors Across',
        'geo_rows': [
            {'place': 'Uganda', 'scope': 'Home Market'},
            {'place': 'East Africa', 'scope': 'Regional'},
            {'place': 'Africa', 'scope': 'Continental'},
            {'place': 'International Markets', 'scope': 'Global'},
        ],
        'geo_foot': 'Consultations available in person in Kampala and virtually for regional and international clients.',
        'instruments_eyebrow': 'Core Instruments',
        'instruments_title_html': 'Traded Across <em>Spot & Futures</em>',
        'instruments': [
            {'name': 'Bitcoin', 'sym': 'BTC', 'text': 'The portfolio\'s strategic core — the most liquid, institutionally adopted digital asset, allocated across full market cycles with hedged futures overlays.'},
            {'name': 'Ethereum', 'sym': 'ETH', 'text': 'Primary smart-contract exposure capturing the growth of on-chain finance, staking economics, and digital asset infrastructure.'},
            {'name': 'Solana', 'sym': 'SOL', 'text': 'High-throughput network exposure with disciplined sizing — a higher-beta allocation managed under strict volatility-aware limits.'},
            {'name': 'BNB', 'sym': 'BNB', 'text': 'Exchange-ecosystem asset providing diversified exposure to digital asset market activity and liquidity flows.'},
            {'name': 'Zcash', 'sym': 'ZEC', 'text': 'Selective privacy-asset allocation held within defined exposure limits as a satellite position in the broader framework.'},
        ],
    },
    'clients': {
        'eyebrow': 'Client Profile',
        'title_html': 'Who We <em>Serve</em>',
        'lead': 'We work with a select group of investors who value discipline, discretion, and a long-term partnership.',
        'cards': ['High-Net-Worth Individuals', 'Entrepreneurs', 'Corporate Executives', 'Family Offices', 'Private Equity Professionals', 'Institutional Investors', 'Corporate Treasuries', 'Sophisticated Investors'],
    },
    'institutional': {
        'eyebrow': 'Institutional Mandates',
        'title_html': 'Structured Engagement for <em>Serious Capital</em>',
        'lead': 'Mandates are accepted selectively, following a suitability and risk review. Every engagement is governed by documented terms, defined risk parameters, and a structured reporting cadence.',
        'list': [
            {'mk': 'I', 'title': 'Discretionary Portfolio Mandates', 'text': 'Professional management of digital asset allocations under agreed objectives, exposure limits, and drawdown controls.'},
            {'mk': 'II', 'title': 'Advisory & Treasury Mandates', 'text': 'Non-discretionary guidance for institutions, corporate treasuries, and family offices building digital asset programs.'},
            {'mk': 'III', 'title': 'Structured Reporting', 'text': 'Periodic performance and exposure reporting, with transparent documentation of strategy, risk posture, and changes.'},
            {'mk': 'IV', 'title': 'Family Office Services', 'text': 'Multi-generational digital asset planning, governance frameworks, and education for principals and their advisers.'},
        ],
        'tiers': [
            {'amount': 'USD 25,000', 'title': 'Private Client Mandates', 'text': 'Individual investors, entrepreneurs, and executives establishing a professionally managed digital asset allocation.'},
            {'amount': 'USD 100,000', 'title': 'Institutional Mandates', 'text': 'Institutions, family offices, corporate treasuries, and investment firms seeking discretionary or advisory engagement.'},
        ],
        'disclaimer': 'Minimums are indicative and subject to suitability review. Acceptance of any mandate is at sole discretion and does not constitute an offer of investment services in any jurisdiction where such an offer would be unlawful.',
        'cta': 'Discuss a Mandate',
    },
    'calculator': {
        'eyebrow': 'Investment Calculator',
        'title_html': 'Model Your <em>Capital Trajectory</em>',
        'lead': 'Explore illustrative growth scenarios using your own assumptions. Adjust capital, contributions, horizon, and an assumed annual rate — then review the projection year by year.',
        'disclaimer': '<strong>Important:</strong> This calculator is a hypothetical, educational illustration only. It assumes a constant rate of return compounded monthly, which does not reflect how markets behave — digital assets are highly volatile and can produce significant losses, including loss of principal. The scenarios shown are assumptions you control, not forecasts, projections, or promises of performance. Historical results, including any past performance referenced on this site, do not guarantee future outcomes. This tool does not constitute investment advice; consult qualified professional advisers before making investment decisions.',
    },
    'insights': {
        'eyebrow': 'Insights & Market Commentary',
        'title_html': 'Research-Driven <em>Perspective</em>',
        'lead': 'Selected commentary on digital assets, market cycles, and the African investment landscape.',
    },
    'process': {
        'eyebrow': 'Client Onboarding',
        'title_html': 'A Structured Path to <em>Partnership</em>',
        'steps': [
            {'num': 1, 'title': 'Discovery Call', 'text': 'A confidential conversation about your objectives, time horizon, and current portfolio.'},
            {'num': 2, 'title': 'Suitability & Risk Review', 'text': 'Assessment of risk tolerance, liquidity needs, and investment constraints.'},
            {'num': 3, 'title': 'Strategy Proposal', 'text': 'A documented framework outlining allocation, risk controls, and reporting cadence.'},
            {'num': 4, 'title': 'Onboarding & Monitoring', 'text': 'Implementation with ongoing monitoring, communication, and periodic reviews.'},
        ],
    },
    'contact': {
        'eyebrow': 'Begin the Conversation',
        'title_html': 'Ready to Build a Smarter <em>Investment Strategy?</em>',
        'lead': 'Partner with a disciplined wealth management professional focused on capital preservation, strategic growth, and long-term wealth creation.',
        'form_title': 'Request an Investment Review',
        'form_sub': 'All enquiries are confidential. Expect a response within one business day.',
        'form_note': 'By submitting, you consent to being contacted about your enquiry. Submitting this form does not create an advisory relationship. Investments involve risk, including possible loss of principal.',
    },
    'investor-portal': {
        'eyebrow': 'Client Portal',
        'title_html': 'Become an <em>Investor</em>',
        'lead': 'Register for secure access to your portfolio dashboard, documents, and advisor communications — or sign in if you already have an account.',
        'register_label': 'Create Investor Account',
        'login_label': 'Sign In to Portal',
        'note': 'New registrations are reviewed by our advisory team. Portal access is activated after approval.',
        'register_url': '/investor/register',
        'login_url': '/investor/login',
    },
}
