# Generated by Django 6.0.6 on 2026-06-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='page_key',
            field=models.SlugField(blank=True, help_text='Matches data-section on the public frontend HTML', max_length=80),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('ticker', 'Live Ticker'), ('strip', 'Brand Strip'), ('about', 'About'), ('stats', 'Track Record / Stats'), ('philosophy', 'Philosophy'), ('services', 'Services'), ('why', 'Why Choose Us'), ('risk', 'Risk Management'), ('markets', 'Markets'), ('clients', 'Clients'), ('institutional', 'Institutional'), ('calculator', 'Calculator'), ('insights', 'Insights'), ('process', 'Process'), ('contact', 'Contact'), ('custom', 'Custom content'), ('html', 'Raw HTML')], default='custom', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('page_key', ''), _negated=True), fields=('page_key',), name='unique_nonempty_page_key'),
        ),
    ]
