# Generated by Django 6.0.6 on 2026-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_section_page_key_alter_section_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navigation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
