# Generated by Django 6.0.6 on 2026-07-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='InvestorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alert_date', models.CharField(blank=True, max_length=40)),
                ('alert_type', models.CharField(default='info', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorCurrencySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(default='USD', max_length=10)),
                ('to_currency', models.CharField(default='UGX', max_length=10)),
                ('rate_label', models.CharField(blank=True, max_length=80)),
                ('from_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_setting', to='investors.investorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('crypto', 'Crypto'), ('stocks', 'Stocks'), ('bonds', 'Bonds'), ('commodities', 'Commodities'), ('real_estate', 'Real Estate'), ('cash', 'Cash')], default='crypto', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('holdings_text', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('change_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_flex', models.BooleanField(default=False, help_text='Counts toward available flex funds')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorMarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value_display', models.CharField(max_length=40)),
                ('change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorOtcTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('side', models.CharField(blank=True, max_length=20)),
                ('amount_display', models.CharField(blank=True, max_length=40)),
                ('settlement', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otc_trades', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorSmartIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('min_investment', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_ideas', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('net_worth', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('flex_funds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['-as_of_date', '-id'],
                'unique_together': {('investor', 'as_of_date')},
            },
        ),
    ]
