# Generated by Django 6.0.6 on 2026-07-01 19:18

import apps.investors.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_migrate_portfolio_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('country_of_residence', models.CharField(blank=True, max_length=80)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's license")], max_length=30)),
                ('id_number', models.CharField(blank=True, max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('source_of_funds', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='investors.investorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor KYC',
                'verbose_name_plural': 'Investor KYC records',
            },
        ),
        migrations.CreateModel(
            name='InvestorKycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_front', 'Government ID (front)'), ('id_back', 'Government ID (back)'), ('proof_of_address', 'Proof of address'), ('selfie', 'Selfie with ID')], max_length=30)),
                ('file', models.FileField(upload_to=apps.investors.models.kyc_document_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investors.investorkyc')),
            ],
            options={
                'ordering': ['doc_type'],
                'unique_together': {('kyc', 'doc_type')},
            },
        ),
    ]
