# Generated by Django 6.0.6 on 2026-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_investor_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='investormarketitem',
            name='binance_symbol',
            field=models.CharField(blank=True, help_text='Optional Binance pair for live prices, e.g. btcusdt', max_length=20),
        ),
        migrations.AlterField(
            model_name='investormarketitem',
            name='value_display',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
