# Generated by Django 6.0.6 on 2026-06-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_investors',
            field=models.BooleanField(default=False),
        ),
    ]
